/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package seakers.formationsimulator;


public enum Frame implements org.apache.thrift.TEnum {
  INERTIAL(1),
  LVLH(2);

  private final int value;

  private Frame(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Frame findByValue(int value) { 
    switch (value) {
      case 1:
        return INERTIAL;
      case 2:
        return LVLH;
      default:
        return null;
    }
  }
}
